# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeseries-data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timeseries-data.proto',
  package='galvanalyser',
  syntax='proto3',
  serialized_pb=_b('\n\x15timeseries-data.proto\x12\x0cgalvanalyser\"4\n\tDataRange\x12\x17\n\x0fstart_sample_no\x18\x01 \x01(\x03\x12\x0e\n\x06values\x18\x02 \x03(\x01\"\\\n\nDataRanges\x12\x12\n\ndataset_id\x18\x01 \x01(\x03\x12\x11\n\tcolumn_id\x18\x02 \x01(\x03\x12\'\n\x06ranges\x18\x03 \x03(\x0b\x32\x17.galvanalyser.DataRangeb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATARANGE = _descriptor.Descriptor(
  name='DataRange',
  full_name='galvanalyser.DataRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_sample_no', full_name='galvanalyser.DataRange.start_sample_no', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='galvanalyser.DataRange.values', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=91,
)


_DATARANGES = _descriptor.Descriptor(
  name='DataRanges',
  full_name='galvanalyser.DataRanges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset_id', full_name='galvanalyser.DataRanges.dataset_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column_id', full_name='galvanalyser.DataRanges.column_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ranges', full_name='galvanalyser.DataRanges.ranges', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=185,
)

_DATARANGES.fields_by_name['ranges'].message_type = _DATARANGE
DESCRIPTOR.message_types_by_name['DataRange'] = _DATARANGE
DESCRIPTOR.message_types_by_name['DataRanges'] = _DATARANGES

DataRange = _reflection.GeneratedProtocolMessageType('DataRange', (_message.Message,), dict(
  DESCRIPTOR = _DATARANGE,
  __module__ = 'timeseries_data_pb2'
  # @@protoc_insertion_point(class_scope:galvanalyser.DataRange)
  ))
_sym_db.RegisterMessage(DataRange)

DataRanges = _reflection.GeneratedProtocolMessageType('DataRanges', (_message.Message,), dict(
  DESCRIPTOR = _DATARANGES,
  __module__ = 'timeseries_data_pb2'
  # @@protoc_insertion_point(class_scope:galvanalyser.DataRanges)
  ))
_sym_db.RegisterMessage(DataRanges)


# @@protoc_insertion_point(module_scope)
