/* tslint:disable */
/* eslint-disable */
/**
 * Battery Data API
 * A standard API for accessing battery experiment datasets and metadata
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: martin.robinson@cs.ox.ac.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

