# Generated by Django 4.1.4 on 2023-02-20 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.PositiveBigIntegerField()),
                ('column_id', models.PositiveIntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'timeseries_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField(null=True, unique=True)),
                ('uid', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CellFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('form_factor', models.TextField()),
                ('link_to_datasheet', models.TextField()),
                ('anode_chemistry', models.TextField()),
                ('cathode_chemistry', models.TextField()),
                ('nominal_capacity', models.FloatField()),
                ('nominal_cell_weight', models.FloatField()),
                ('manufacturer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('date', models.DateTimeField()),
                ('type', models.TextField(null=True)),
                ('purpose', models.TextField()),
                ('json_data', models.JSONField(null=True)),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='galvanalyser.cell')),
            ],
        ),
        migrations.CreateModel(
            name='DataUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('symbol', models.TextField()),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('api_key', models.TextField(null=True)),
                ('last_check_in', models.DateTimeField(null=True)),
                ('sleep_time', models.IntegerField(default=10)),
                ('admin_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editable_harvesters', to='auth.group')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readable_harvesters', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('stable_time', models.PositiveSmallIntegerField(default=60)),
                ('admin_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editable_paths', to='auth.group')),
                ('harvester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_paths', to='galvanalyser.harvester')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readable_paths', to='auth.group')),
            ],
            options={
                'unique_together': {('harvester', 'path')},
            },
        ),
        migrations.CreateModel(
            name='VouchFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vouched_for', to=settings.AUTH_USER_MODEL)),
                ('vouching_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vouched_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeseriesRangeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('range_start', models.PositiveBigIntegerField()),
                ('range_end', models.PositiveBigIntegerField()),
                ('info', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_labels', to='galvanalyser.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ObservedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.TextField()),
                ('last_observed_size', models.PositiveBigIntegerField(default=0)),
                ('last_observed_time', models.DateTimeField(null=True)),
                ('state', models.TextField(choices=[('RETRY IMPORT', 'Retry Import'), ('IMPORT FAILED', 'Import Failed'), ('UNSTABLE', 'Unstable'), ('GROWING', 'Growing'), ('STABLE', 'Stable'), ('IMPORTING', 'Importing'), ('IMPORTED', 'Imported')], default='UNSTABLE')),
                ('monitored_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='galvanalyser.monitoredpath')),
            ],
            options={
                'unique_together': {('monitored_path', 'relative_path')},
            },
        ),
        migrations.CreateModel(
            name='HarvestError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='galvanalyser.observedfile')),
                ('harvester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='galvanalyser.harvester')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galvanalyser.monitoredpath')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('type', models.TextField()),
                ('datasets', models.ManyToManyField(related_name='equipment', to='galvanalyser.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datasets', to='galvanalyser.observedfile'),
        ),
        migrations.CreateModel(
            name='DataColumnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galvanalyser.dataunit')),
            ],
            options={
                'unique_together': {('unit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='galvanalyser.dataset')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galvanalyser.datacolumntype')),
            ],
            options={
                'unique_together': {('dataset', 'name')},
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cells', to='galvanalyser.cellfamily'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('file', 'date')},
        ),
        migrations.CreateModel(
            name='DataColumnStringKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveBigIntegerField()),
                ('string', models.TextField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_keys', to='galvanalyser.datacolumn')),
            ],
            options={
                'unique_together': {('column', 'key', 'string')},
            },
        ),
    ]
