# Generated by Django 4.1.4 on 2023-02-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galvanalyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvesterror',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='galvanalyser.observedfile'),
        ),
    ]
