# Generated by Django 4.1.4 on 2023-02-20 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galvanalyser', '0002_alter_harvesterror_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VouchFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vouched_for', to=settings.AUTH_USER_MODEL)),
                ('vouching_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vouched_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
