FROM node:lts@sha256:132309f5136555725debd57b711eb4b329fff22a00588834dbec391a3f9782cf
RUN mkdir -p /app
WORKDIR /app
COPY . /app

# Required to get react running:
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN yarn install