# SPDX-License-Identifier: BSD-2-Clause
# Copyright  (c) 2020-2023, The Chancellor, Masters and Scholars of the University
# of Oxford, and the 'Galvanalyser' Developers. All rights reserved.

FROM node:lts@sha256:132309f5136555725debd57b711eb4b329fff22a00588834dbec391a3f9782cf

RUN mkdir -p /app
WORKDIR /app
COPY . /app

# Required to get react running:
ENV NODE_OPTIONS=--openssl-legacy-provider

# Make react-scripts serve on desired port
ENV PORT=80

RUN yarn install
RUN ["/bin/sh", "-c", "./inject_envvars.sh"]
