version: "2"
services:
  app:
    image: app
    build:
      dockerfile: Dockerfile
      context: ./django
    depends_on:
      - postgres
    ports:
      - "5001:5000"
    volumes:
     - ./django:/usr/app
    restart: unless-stopped
    working_dir: /usr/app
    command: ./server.sh
#    command: tail -F anything
    env_file:
     - ./.env
     - ./django/.env.secret

  harvester:
    build:
      dockerfile: Dockerfile
      context: ./harvester
    command: python start.py --name "harvey" --url http://app:5000/ --user_id 42 --run_foreground --restart
#    command: tail -F anything
    depends_on:
      - app
    volumes:
     - ./harvester:/usr/harvester
     - ./.harvester:/harvester_files
     - "${GALVANALYSER_HARVESTER_TEST_PATH}:/usr/test_data"
     - "${GALVANALYSER_HARVESTER_BASE_PATH}:/usr/data"
    working_dir: /usr/harvester

  frontend:
    image: frontend_dev
    build:
      dockerfile: Dockerfile_dev
      context: ./frontend
    ports:
      - "3000:3000"
    command: yarn start
