version: "2"
services:
  galvanalyser_app:
    image: galvanalyser_app
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - galvanalyser_redis
      - galvanalyser_rabbitmq
      - galvanalyser_postgres
    ports:
      - "5001:5000"
    volumes:
     - ./backend:/usr/app
     - "${GALVANALYSER_HARVESTER_TEST_PATH}:/usr/test_data"
     - "${GALVANALYSER_HARVESTER_BASE_PATH}:/usr/data"
     - "${CELERY_LOG_DIR}:/var/log/celery"
    restart: unless-stopped
    working_dir: /usr/app
    command: ./server.sh 
    restart: unless-stopped
    env_file:
     - ./.env
  galvanalyser_worker:
    image: galvanalyser_app
    command: ./worker.sh 
    depends_on:
      - galvanalyser_app
    volumes:
     - ./backend:/usr/app
     - "${GALVANALYSER_HARVESTER_BASE_PATH}:/usr/data"
     - "${CELERY_LOG_DIR}:/var/log/celery"

    working_dir: /usr/app
    restart: unless-stopped
    env_file:
     - ./.env
  galvanalyser_frontend:
    image: galvanalyser_frontend_dev
    build:
      dockerfile: Dockerfile_dev
      context: ./frontend
    depends_on:
      - galvanalyser_app
    ports:
      - "3000:3000"
    volumes:
     - ./frontend:/app
    restart: unless-stopped
    working_dir: /app
    command: yarn start 
    restart: unless-stopped
    env_file:
     - ./.env
  galvanalyser_rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
    env_file:
      - ./.env
    restart: unless-stopped
  galvanalyser_redis:
    image: redis:5.0-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
     - "6379:6379"
    volumes:
     - "${REDIS_DATA_PATH}:/var/lib/redis"
  galvanalyser_postgres:
    image: "postgres"
    stop_signal: SIGINT                 # Fast Shutdown mode
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - "${GALVANALYSER_DATA_PATH}:/var/lib/postgresql/data"
    env_file:
      - ./.env
    restart: unless-stopped
  
