version: "2"
services:

  postgres:
    image: "postgres"
    stop_signal: SIGINT                 # Fast Shutdown mode
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - "${GALVANALYSER_DATA_PATH}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "galvanalyser"
    restart: unless-stopped

  app_test:
    build:
      dockerfile: Dockerfile-test
      context: backend
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    volumes:
     - ./backend:/usr/app
    restart: unless-stopped
    working_dir: /usr/app
    command: ./server.sh
#    command: tail -F anything
    environment:
      POSTGRES_PASSWORD: "galvanalyser"
      DJANGO_SECRET_KEY: "long-and-insecure-key-12345"
      DJANGO_TEST: "TRUE"
