version: "2"
services:
  app:
    image: app
    build:
      dockerfile: Dockerfile
      context: backend
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
     - ./backend:/usr/app
    restart: unless-stopped
    working_dir: /usr/app
    command: ./server.sh
#    command: tail -F anything
    env_file:
     - ./.env
     - backend/.env.secret

  harvester:
    build:
      dockerfile: Dockerfile
      context: ./harvester
    command: python start.py --name "harvey" --url http://app:5000/ --user_id 42 --run_foreground --restart
#    command: tail -F anything
    depends_on:
      - app
    restart: unless-stopped
    volumes:
     - ./harvester:/usr/harvester
     - ./.harvester:/harvester_files
     - "${GALVANALYSER_HARVESTER_TEST_PATH}:/usr/test_data"
     - "${GALVANALYSER_HARVESTER_BASE_PATH}:/usr/data"
    working_dir: /usr/harvester

  frontend:
    image: frontend_dev
    build:
      dockerfile: Dockerfile_dev
      context: ./frontend
    ports:
      - "3000:3000"
    command: yarn start
    restart: unless-stopped

#  old_worker:
#      build:
#        dockerfile: Dockerfile
#        context: ./backend
#      command: python manage.py test
#      depends_on:
#        - postgres
#      volumes:
#       - ./backend:/usr/app
#       - "${GALVANALYSER_HARVESTER_BASE_PATH}:/usr/data"
#       - "${GALVANALYSER_HARVESTER_TEST_PATH}:/usr/test_data"
#       - "${CELERY_LOG_DIR}:/var/log/celery"
#      working_dir: /usr/app
#      env_file:
#       - ./.env
