version: "2"
services:
  app:
    image: app
    build:
      dockerfile: Dockerfile
      context: backend
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
     - ./backend:/usr/app
    working_dir: /usr/app
    env_file:
     - ./.env
     - ./.env.secret
    restart: unless-stopped
    command: ./server.sh

  frontend:
    image: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        FRONTEND_PORT: ${FRONTEND_PORT?80}
    depends_on:
      - app
    ports:
      - "${FRONTEND_PORT?80}:${FRONTEND_PORT?80}"
    env_file:
     - ./.env
    restart: unless-stopped

  postgres:
    image: "postgres"
    stop_signal: SIGINT                 # Fast Shutdown mode
    ports:
      - "5433:5433"
    volumes:
      - "${GALVANALYSER_DATA_PATH}:/var/lib/postgresql/data"
    env_file:
      - ./.env
      - ./.env.secret
    restart: unless-stopped
    command: -p 5433
