version: '3'
services:
  galvanalyserapp:
    build:
      dockerfile: ./webstack/dashapp/Dockerfile
      context: ../
    volumes:
     - ../galvanalyser/webapp:/usr/src/app
  nginx:
    image: "nginx"
    ports:
     - "8081:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    image: "redis"
  postgres:
    image: "postgres"
    stop_signal: SIGINT                 # Fast Shutdown mode
    ports:
      - "5432:5432"
    volumes:
      - /Users/luke/projects/battery/docker/postgres:/var/lib/postgresql/data