version: '3'
services:
  galvanalyserapp:
    build:
      dockerfile: ./webstack/dashapp/Dockerfile
      context: ../
    volumes:
     - ../galvanalyser/harvester:/usr/src/app/galvanalyser/harvester
     - ../galvanalyser/webapp:/usr/src/app/galvanalyser/webapp
     - ../webapp-static-content:/usr/src/app/static_content
    restart: unless-stopped
    working_dir: /usr/src/app/galvanalyser/webapp
    command: python manage.py run -h 0.0.0.0
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    env_file:
     - ./.env.app
  nginx:
    image: "nginx"
    ports:
     - "8081:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../webapp-static-content/libs:/var/www/webapp-static/libs:ro
      - ../webapp-static-content/css:/var/www/webapp-static/css:ro
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any
        delay: 5s
  postgres:
    image: "postgres"
    stop_signal: SIGINT                 # Fast Shutdown mode
    ports:
      - "5432:5432"
    volumes:
      - "${PG_DATA_PATH}:/var/lib/postgresql/data"
    env_file:
      - ./.env.db
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any
        delay: 5s
