# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: placeholder.proto

import sys

_b = (
    sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
)
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="placeholder.proto",
    package="galvanalyser",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x11placeholder.proto\x12\x0cgalvanalyser"\x1b\n\x0b\x44\x61taMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\x62\x06proto3'
    ),
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_DATAMESSAGE = _descriptor.Descriptor(
    name="DataMessage",
    full_name="galvanalyser.DataMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="data",
            full_name="galvanalyser.DataMessage.data",
            index=0,
            number=1,
            type=1,
            cpp_type=5,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=35,
    serialized_end=62,
)

DESCRIPTOR.message_types_by_name["DataMessage"] = _DATAMESSAGE

DataMessage = _reflection.GeneratedProtocolMessageType(
    "DataMessage",
    (_message.Message,),
    dict(
        DESCRIPTOR=_DATAMESSAGE,
        __module__="placeholder_pb2"
        # @@protoc_insertion_point(class_scope:galvanalyser.DataMessage)
    ),
)
_sym_db.RegisterMessage(DataMessage)


# @@protoc_insertion_point(module_scope)
