# Generated by Django 4.1.4 on 2022-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galvanalyser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='username',
            field=models.TextField(null=True, unique=True),
        ),
    ]
