name: Unit Tests (Docker)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test-harvester:
    runs-on: ubuntu-latest
    env:
      GALVANALYSER_HARVESTER_TEST_PATH: /home/mrobins/git/tmp/test_datafiles
    steps:
      - uses: actions/checkout@v2

      - name: Install smbclient
        run: |
          sudo apt-get update
          sudo apt-get install -y smbclient

      - name: Download test suite
        env:
          LIIONSDEN_SMB_PATH: ${{ secrets.LIIONSDEN_SMB_PATH }}
          LIIONSDEN_SMB_USERNAME: ${{ secrets.LIIONSDEN_SMB_USERNAME}}
          LIIONSDEN_SMB_PASSWORD: ${{ secrets.LIIONSDEN_SMB_PASSWORD}}
        run: |
          sudo mkdir -p $GALVANALYSER_HARVESTER_TEST_PATH 
          cd $GALVANALYSER_HARVESTER_TEST_PATH
          sudo smbget -R $LIIONSDEN_SMB_PATH/test-suite-small -U "$LIIONSDEN_SMB_USERNAME%$LIIONSDEN_SMB_PASSWORD"

      - name: Build the stack
        run: touch .env.secret && docker-compose -f docker-compose.dev.yml build harvester

      - name: Run tests
        run: docker-compose -f docker-compose.dev.yml run --rm harvester cd /usr && python -m unittest discover -s /usr/harvester/test

  test-backend:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: "galvanalyser"
      DJANGO_SECRET_KEY: "long-and-insecure-key-12345"
      DJANGO_TEST: "TRUE"
    steps:
      - uses: actions/checkout@v2

      - name: Build the stack
        run: docker-compose -f docker-compose.test.yml up --detach --build

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml run --rm app_test python manage.py test
