name: Unit Tests (Docker)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GALVANALYSER_HARVESTER_TEST_PATH: /home/mrobins/git/tmp/galvanalyser_test_datafiles
    steps:
      - uses: actions/checkout@v2

      - name: Install smbclient
        run: |
          sudo apt-get update
          sudo apt-get install -y smbclient

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache test suite
        id: cache-test-suite
        uses: actions/cache@v2
        with:
          path: ${{ env.GALVANALYSER_HARVESTER_TEST_PATH }}
          key: test-suite-${{ steps.get-date.outputs.date }}

      - name: Download test suite
        if: steps.cache-test-suite.outputs.cache-hit != 'true'
        env:
          LIIONSDEN_SMB_PATH: ${{ secrets.LIIONSDEN_SMB_PATH }}
          LIIONSDEN_SMB_USERNAME: ${{ secrets.LIIONSDEN_SMB_USERNAME}}
          LIIONSDEN_SMB_PASSWORD: ${{ secrets.LIIONSDEN_SMB_PASSWORD}}
        run: |
          sudo mkdir -p $GALVANALYSER_HARVESTER_TEST_PATH 
          cd $GALVANALYSER_HARVESTER_TEST_PATH
          sudo smbget -R $LIIONSDEN_SMB_PATH/test-suite-small -U "$LIIONSDEN_SMB_USERNAME%$LIIONSDEN_SMB_PASSWORD"

      - name: Build the stack
        run: docker-compose up --detach --build

      - name: Run tests
        run: docker-compose run --rm galvanalyser_app python manage.py test

